# Generated by Django 4.2.8 on 2023-12-31 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageTask', '0005_remove_task_user_task_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AddField(
            model_name='history',
            name='employee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='manageTask.employee'),
        ),
    ]
